### ISSUE TITLE
API returning 502

### ISSUE THREAD

**Issue by bmustill-rose** [jameskozlowski/randomnumberapi#2]
The API is currently returning 502 bad gateway when queried.

**Comment by jameskozlowski** [comment]
I brought it back up, out of curiosity what are you using it for?

**Comment by bmustill-rose** [comment]
Unfortunately I didn't recieve a notification for your comment for some reason. Apologies.

I've built a social media management system for a charity that can't afford a commercial offering. It uses your random number generator with the Reddit seed to choose what to Tweet based on a list of Tweets.

I notice that the API is down once again. If it's not going to cost you huge amounts of time / money I would appreciate it if it could be brought back up but I understand if you'd rather not.

Many thanks for the service regardless - it's served us well for around 10 months and in turn drastically increased our social media reach.

**Comment by jameskozlowski** [comment]
ok, neat I was just curious. It is back up now. I will look into fixing the problem permanently next week
