### ISSUE TITLE
Cors issues when accessing api.

### ISSUE THREAD

**Issue by Avi-E-Koenig** [jameskozlowski/randomnumberapi#4]
Hi,
Please advise...I see no instructions on api docs in regards.

With basic request from multiple domains.

```javascript

fetch('https://www.randomnumberapi.com/api/v1.0/random?min=100&max=1000&count=5')
  .then(response => response.json())
  .then(data => console.log(data));
  
  ```
Generic cors notice :
Access to fetch at 'https://www.randomnumberapi.com/api/v1.0/random?min=100&max=1000&count=5' from origin 'https://www.google.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jameskozlowski** [comment]
I added support for CORS should work now

**Comment by Avi-E-Koenig** [comment]
Thanks!
